apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgrest-cert
spec:
  secretName: postgrest-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: data.test.casperholders.com
  dnsNames:
    - data.test.casperholders.com
