apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casperparser-test-pg-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi