apiVersion: v1
kind: ConfigMap
metadata:
  name: casperparser-config-testnet
data:
  CASPER_PARSER_REDIS: "casperparser-redis-service-testnet:6379"
  CASPER_PARSER_RPC: "http://rpc.testnet.casperholders.com/rpc"
  CASPER_PARSER_DATABASE: "postgres://postgres@casperparser-db-service-testnet:5432/casperparser-testnet?sslmode=disable"
  CASPER_PARSER_EVENT: "http://node.testnet.casperholders.com:9999/events/main"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config-testnet
data:
  PGRST_DB_URI: "postgres://postgres@casperparser-db-service-testnet:5432/casperparser-testnet"
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "web_anon"
  PGRST_OPENAPI_MODE: "ignore-privileges"
  PGRST_OPENAPI_SERVER_PROX_URI: "https://data.testnet.casperholders.com/swagger"
  PGRST_DB_MAX_ROWS: "100"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: max-conns
data:
  max_conns.sql: "ALTER SYSTEM SET max_connections = 4000;"