apiVersion: v1
kind: PersistentVolume
metadata:
  name: casperparser-testnet-pg-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/casperparser-testnet-pg-volume/"