apiVersion: v1
kind: PersistentVolume
metadata:
  name: casperparser-testnet-pg-volume
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany