apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casperparser-testnet-pg-volume
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi