apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: casperparser-metrics
  labels:
    k8s-apps: http
spec:
  jobLabel: k8s-app
  selector:
    matchExpressions:
      - {key: k8s-app, operator: Exists}
  namespaceSelector:
    matchNames:
      - casperparser
  endpoints:
    - port: http-metrics
      interval: 15s
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: casperparser-state-metrics
    k8s-app: casperparser-state-metrics
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
  name: casperparser-state-metrics
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: asynqmon